### ISSUE TITLE
New stories should automatically switch when option is selected at the start of the game

### ISSUE THREAD

**Issue by The1CABAL** [DevinWalkup/PointPoker#13]
If "Automatically switch to the next story when estimate has been set?" is selected at the start of the game and then all the preplanned stories are completed, the newly added story is not switched to.

**Comment by DevinWalkup** [comment]
Good catch! Thanks for logging the issue. I will get to work on this :)

**Comment by DevinWalkup** [comment]
This issue has been resolved and the update is now live.
